name: Build and publish

on: [workflow_dispatch]

jobs:

  buid:
    name: Gen data and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run sbgraph
      run : |
        curl -LO https://github.com/mamezou-tech/sbgraph/releases/download/v0.4.0/sbgraph-linux-amd64.tar.gz
        tar xvf sbgraph-linux-amd64.tar.gz
        mkdir ~/bin
        export PATH=$PATH:~/bin
        mv sbgraph ~/bin
        sbgraph init
        sbgraph project -p kondoumh
        sbgraph fetch
        sbgraph aggregate
        sbgraph graph -i=true -a=true -j=true
        sbgraph project -p help-jp
        sbgraph fetch
        sbgraph aggregate
        sbgraph graph -i=true -a=true -j=true
        ls -l _work/kondoumh | wc -l
        ls -l _work/help-jp | wc -l
        rm -r _work/kondoumh
        rm -r _work/help-jp
        mkdir public/data
        mv _work/help-jp_graph.json public
        mv _work/kondoumh_graph.json public

    - name: Deploy to netlify
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: './public'
        production-branch: master
        github-token: ${{ secrets.GH_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
