name: Build and publish

on: [workflow_dispatch]

jobs:

  buid:
    name: Gen data and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run sbgraph
      run : |
        curl -LO https://github.com/mamezou-tech/sbgraph/releases/download/v0.7.0/sbgraph-linux-amd64.tar.gz
        tar xvf sbgraph-linux-amd64.tar.gz
        mkdir ~/bin
        export PATH=$PATH:~/bin
        mv sbgraph ~/bin
        make build PROJECT=kondoumh
        make build PROJECT=help-jp
        ls -l public

    - name: Deploy to netlify
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: './public'
        production-branch: main
        github-token: ${{ secrets.GH_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
