name: Build and publish

on: [workflow_dispatch]

jobs:

  buid:
    name: Gen data and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run sbgraph
      run : |
        export PATH=$PATH:~/bin
        make install VERSION=v0.7.0
        make build PROJECT=kondoumh
        make build PROJECT=help-jp
        make build PROJECT=comic-forum
        make build PROJECT=icons
        make build PROJECT=daiiz
        make build PROJECT=june29
        ls -l public

    - name: Deploy to netlify
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: './public'
        production-branch: main
        github-token: ${{ secrets.GH_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
